# Generated by Django 5.2.1 on 2025-06-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_created_at_attendance_updated_at_and_more'),
        ('attendance', '0005_merge_20250616_1332'),
    ]

    operations = [
    ]
